name: Lint and Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.os }}
        
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install yapf toml pylint mypy pytest importchecker isort coverage matplotlib numpy
      - name: Check for unused imports
        run: importchecker .
      - name: Coding style
        run: isort . && yapf --diff yaptool.py test_yaptool.py
      - name: Linting
        run: pylint yaptool.py test_yaptool.py
      - name: Type checking
        run: mypy yaptool.py test_yaptool.py
      - name: Test suite incl. coverage report
        run: coverage run -m pytest && coverage report -m
